packages:
  - packages/api
  - packages/common
  - packages/config
  - packages/console
  - packages/marketing
  - packages/prisma
catalog:
  '@phosphor-icons/react': ~2.1.5
  '@prisma/client': ~6.1.0
  '@radix-ui/react-navigation-menu': ~1.2.3
  '@radix-ui/react-tooltip': ~1.1.6
  axios: ~1.8.2
  class-variance-authority: ~0.7.1
  date-fns: ~3.6.0
  graphql: ~16.8.1
  prisma: ~6.1.0
  react: ~18.3.1
  react-dom: ~18.3.1
  react-twc: ~1.4.2
  tailwind-merge: ~2.2.1
  zod: ~3.25.65
onlyBuiltDependencies:
  - puppeteer
  - sharp
