version: '3'
networks:
  default:
    name: automa
services:
  postgres:
    container_name: automa-postgres
    image: automa/postgres
    build: ../db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: automa
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    container_name: automa-redis
    image: redis:alpine
    ports:
      - 6379:6379
  jaeger:
    container_name: automa-jaeger
    image: jaegertracing/all-in-one
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
  prometheus:
    container_name: automa-prometheus
    image: prom/prometheus
    ports:
      - 16687:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - host.docker.internal:host-gateway
