version: '3'
networks:
  default:
    name: automa
services:
  postgres:
    container_name: postgres
    image: automa/postgres
    build: ../db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: automa
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
