module.exports = {
  apps: [
    {
      name: 'prisma-dev',
      cwd: 'packages/prisma',
      script: 'yarn',
      interpreter: '/bin/bash',
      args: 'dev',
    },
    {
      name: 'common-dev',
      cwd: 'packages/common',
      script: 'yarn',
      interpreter: '/bin/bash',
      args: 'dev',
    },
    {
      name: 'config-dev',
      cwd: 'packages/config',
      script: 'yarn',
      interpreter: '/bin/bash',
      args: 'dev',
    },
    {
      name: 'graphql-dev',
      watch: [
        'packages/api/src/graphql/schema',
        'packages/console/src/**/*.queries.ts',
      ],
      script: 'yarn',
      interpreter: '/bin/bash',
      args: 'generate-graphql',
      autorestart: false,
    },
    {
      name: 'api-dev',
      cwd: 'packages/api',
      script: 'yarn',
      interpreter: '/bin/bash',
      args: 'dev',
    },
    {
      name: 'api-graphql-dev',
      cwd: 'packages/api',
      watch: ['src/graphql/schema'],
      script: 'yarn',
      interpreter: '/bin/bash',
      args: 'copy-graphql',
      autorestart: false,
    },
    {
      name: 'api',
      cwd: 'packages/api',
      watch: ['build'],
      script: 'build/index.js',
    },
    {
      name: 'console',
      cwd: 'packages/console',
      script: 'yarn',
      interpreter: '/bin/bash',
      args: 'start',
    },
  ],
};
