name: Build check (docs)
on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/build-check-docs.yml
      - packages/docs/components/**
      - packages/docs/pages/**
      - packages/docs/next.config.js
      - packages/docs/tailwind.config.ts
      - packages/docs/theme.config.tsx
      - pnpm-lock.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 'node_modules'
          key: deps-${{ hashFiles('**/pnpm-lock.yaml', '**/schema.prisma') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Compile typescript
        run: pnpm --filter @automa/common build
      - name: Build site
        run: pnpm build
        working-directory: packages/docs
