name: Deploy Staging
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/deploy-staging.yml
      - public/**
      - src/**
      - next.config.mjs
      - tailwind.config.ts
      - pnpm-lock.yaml
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 'node_modules'
          key: deps-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build site
        env:
          NEXT_PUBLIC_NODE_ENV: staging
        run: pnpm build
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.STAGING_AWS_REGION }}
        run: |
          aws s3 sync build s3://${{ secrets.STAGING_AWS_S3_BUCKET }} \
            --exclude '*.html' \
            --cache-control max-age=31536000
          aws s3 sync build s3://${{ secrets.STAGING_AWS_S3_BUCKET }} \
            --exclude '*' --include '*.html'
