name: Deploy Production (frontend)
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/deploy-production-frontend.yml
      - packages/frontend/public/**
      - packages/frontend/src/**
      - packages/frontend/index.html
      - packages/frontend/vite.config.ts
      - yarn.lock
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy-production-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: deps-${{ hashFiles('**/yarn.lock', '**/schema.prisma') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Compile typescript
        run: yarn workspace @automa/common build
      - name: Build site
        run: yarn build
        working-directory: packages/frontend
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID_FRONTEND }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY_FRONTEND }}
          AWS_REGION: ${{ secrets.PRODUCTION_AWS_REGION_FRONTEND }}
        run: aws s3 sync packages/frontend/build s3://${{ secrets.PRODUCTION_AWS_S3_BUCKET_FRONTEND }}
      - name: Invalidate cloudfront cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID_FRONTEND }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY_FRONTEND }}
          AWS_REGION: ${{ secrets.PRODUCTION_AWS_REGION_FRONTEND }}
        run: aws cloudfront create-invalidation
          --distribution-id ${{ secrets.PRODUCTION_AWS_CLOUDFRONT_DISTRIBUTION_FRONTEND }}
          --paths '/index.html'
