name: Linting
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    needs: [lockfile, lint]
    if: always()
    steps:
      - name: Wait for checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          match_pattern: lockfile|lint|test-api|test-config|test-console|test-db|chromatic-console|chromatic-marketing|relative-console|relative-marketing
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Cache dependencies
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: 'node_modules'
          key: deps-${{ hashFiles('**/pnpm-lock.yaml', '**/schema.prisma') }}
          restore-keys: |
            deps-
      - name: Lockfile check
        run: |
          pnpm install
          git diff --exit-code
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 'node_modules'
          key: deps-${{ hashFiles('**/pnpm-lock.yaml', '**/schema.prisma') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Compile typescript
        run: |
          pnpm --filter @automa/prisma build
          pnpm --filter @automa/common build
      - name: GraphQL types check
        run: |
          pnpm graphql-generate
          git diff --exit-code
      - name: Lint check
        run: pnpm lint
      - name: Lint fix check
        run: |
          pnpm lint-fix
          git diff --exit-code
      - name: Formatting check
        run: pnpm format-check
