name: Linting
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 'node_modules'
          key: deps-${{ hashFiles('**/pnpm-lock.yaml', '**/schema.prisma') }}
          restore-keys: |
            deps-
      - name: Lockfile check
        run: |
          pnpm install
          git diff --exit-code
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 'node_modules'
          key: deps-${{ hashFiles('**/pnpm-lock.yaml', '**/schema.prisma') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: GraphQL types check
        run: |
          pnpm generate-graphql
          git diff --exit-code
      - name: Lint check
        run: pnpm lint
      - name: Formatting check
        run: pnpm format-check
