name: RelativeCI (console)
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/relative-console.yml
      - packages/console/public/**
      - packages/console/src/**
      - packages/console/index.html
      - packages/console/vite.config.ts
      - yarn.lock
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/relative-console.yml
      - packages/console/public/**
      - packages/console/src/**
      - packages/console/index.html
      - packages/console/vite.config.ts
      - yarn.lock
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'push' && github.run_number }}
  cancel-in-progress: true
jobs:
  relative-console:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: deps-${{ hashFiles('**/yarn.lock', '**/schema.prisma') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Compile typescript
        run: yarn workspace @automa/common build
      - name: Build stats
        run: yarn build-stats
        working-directory: packages/console
      - name: RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          webpackStatsFile: packages/console/build/webpack-stats.json
          token: ${{ secrets.GITHUB_TOKEN }}
          key: ${{ secrets.RELATIVE_CI_KEY_CONSOLE }}
