name: Testing (db)
on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/test-db.yml
      - db/**
      - pnpm-lock.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 'node_modules'
          key: deps-${{ hashFiles('**/pnpm-lock.yaml', '**/schema.prisma') }}
          restore-keys: |
            deps-
      - name: Install pg_dump
        run: |
          echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get remove --purge postgresql-client-16
          sudo apt-get install -y postgresql-client-17
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Start dependencies
        run: pnpm start-deps
      - name: Schema check
        run: |
          sed -i '/^-- Dumped by pg_dump version/d' db/schema.sql
          git diff --exit-code
